language: python
python:
  - "3.6"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
before_install:
  - mv tests/travis_fullchain.pem /etc/ssl/fullchain.pem
  - mv tests/travis_privkey.pem /etc/ssl/privkey.pem
  - mv tests/travis_secrets.yaml secrets.yaml