language: python
python:
  - "3.6"
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
before_install:
  - mv tests/travis_fullchain.pem travis_fullchain.pem
  - mv tests/travis_privkey.pem travis_privkey.pem
  - mv tests/travis_secrets.yaml secrets.yaml