- alias: Continuous Integration
  trigger:
    - platform: state
      entity_id: sensor.nathanfiscushomeassistant_last_build_state
      to: 'passed'
  action:
    - service: shell_command.updateconfig
    - service: homeassistant.restart