- alias: Lockup
  trigger:
    - platform: event
      event_type: GOODNIGHT_HA
  action:
  - service: cover.close_cover 
    entity_id: cover.garage_door
  - service: media.turn_off
    entity_id: media_player.living_room_tv
  - service: media_player.turn_off
    entity_id: media_player.basement_tv
