- alias: TV Notification - Nate - Work Arrive
  trigger:
    - platform: state
      entity_id: device_tracker.35d6cd65fb3e483f95dcc8b7e8e76d7b
      from: 'not_home'
      to: 'work'
  action:
    - service: notify.livingroom_tv
      data:
        message: "Nate has arrived at work."
        data: 
          icon: "/config/assets/nate.jpg"
    - service: notify.basement_tv
      data:
        message: "Nate has arrived at work."
        data: 
          icon: "/config/assets/nate.jpg"
        
- alias: TV Notification - Nate - Work Leave
  trigger:
    - platform: state
      entity_id: device_tracker.35d6cd65fb3e483f95dcc8b7e8e76d7b
      from: 'work'
      to: 'not_home'
  action:
    - service: notify.livingroom_tv
      data:
        message: "Nate has left work."
        data: 
          icon: "/config/assets/nate.jpg"
    - service: notify.basement_tv
      data:
        message: "Nate has left work."
        data: 
          icon: "/config/assets/nate.jpg"
        
- alias: TV Notification - Nate - Home Leave
  trigger:
    - platform: state
      entity_id: device_tracker.35d6cd65fb3e483f95dcc8b7e8e76d7b
      from: 'home'
      to: 'not_home'
  action:
    - service: notify.livingroom_tv
      data:
        message: "Nate has left home."
        data: 
          icon: "/config/assets/nate.jpg"
    - service: notify.basement_tv
      data:
        message: "Nate has left home."
        data: 
          icon: "/config/assets/nate.jpg"
        
- alias: TV Notification - Nate - Home Arrive
  trigger:
    - platform: state
      entity_id: device_tracker.35d6cd65fb3e483f95dcc8b7e8e76d7b
      from: 'not_home'
      to: 'home'
  action:
    - service: notify.livingroom_tv
      data:
        message: "Nate has arrived home."
        data: 
          icon: "/config/assets/nate.jpg"
    - service: notify.basement_tv
      data:
        message: "Nate has arrived home."
        data: 
          icon: "/config/assets/nate.jpg"