- alias: Living Room TV Notification - Nathan - Work Arrive
  trigger:
    - platform: state
      entity_id: device_tracker.35d6cd65fb3e483f95dcc8b7e8e76d7b
      from: 'not_home'
      to: 'work'
  action:
    service: notify.livingroom_tv
    data:
      message: "Nathan has arrived at work."
      data: 
        icon: "/config/nate.jpg"
        
- alias: Living Room TV Notification - Nathan - Work Leave
  trigger:
    - platform: state
      entity_id: device_tracker.35d6cd65fb3e483f95dcc8b7e8e76d7b
      from: 'work'
      to: 'not_home'
  action:
    service: notify.livingroom_tv
    data:
      message: "Nathan has left work."
      data: 
        icon: "/config/nate.jpg"
        
- alias: Living Room TV Notification - Nathan - Home Leave
  trigger:
    - platform: state
      entity_id: device_tracker.35d6cd65fb3e483f95dcc8b7e8e76d7b
      from: 'home'
      to: 'not_home'
  action:
    service: notify.livingroom_tv
    data:
      message: "Nathan has left home."
      data: 
        icon: "/config/nate.jpg"
        
- alias: Living Room TV Notification - Nathan - Home Arrive
  trigger:
    - platform: state
      entity_id: device_tracker.35d6cd65fb3e483f95dcc8b7e8e76d7b
      from: 'not_home'
      to: 'home'
  action:
    service: notify.livingroom_tv
    data:
      message: "Nathan has arrived home."
      data: 
        icon: "/config/nate.jpg"