- alias: Climate - Open Windows
  trigger:
    - platform: template
      entity_id: sensor.dark_sky_temperature
      value_template: "{% if states.sensor.dark_sky_temperature.state | round(0) - states.sensor.main_floor_temperature | round(0) < 0 %}true{% endif %}"
      for:
        minutes: 5
  action:
    - service: notify.livingroom_tv
      data:
        message: "Its now cool enough to open the windows."
        data: 
          icon: "/config/assets/ha.jpg"
    - service: notify.basement_tv
      data:
        message: "Its now cool enough to open the windows."
        data: 
          icon: "/config/assets/ha.jpg"

- alias: Climate - Close Windows
  trigger:
    - platform: template
      entity_id: sensor.dark_sky_temperature
      value_template: "{% if states.sensor.dark_sky_temperature.state | round(0) - states.sensor.main_floor_temperature | round(0) > 0 %}true{% endif %}"
      for:
        minutes: 5
  action:
    - service: notify.livingroom_tv
      data:
        message: "Its now too warm to have the windows open."
        data: 
          icon: "/config/assets/ha.jpg"
    - service: notify.basement_tv
      data:
        message: "Its now too warm to have the windows open."
        data: 
          icon: "/config/assets/ha.jpg"